apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: vue3-frontend-template
  title: Vue 3 Frontend Template
  description: Generate a Vue 3 project with Vite, ESLint, and optional features.
spec:
  owner: frontend-team
  type: website  # 或 service

  # 用户输入表单（分步骤）
  parameters:
    - title: Project Setup
      required: [name, description]
      properties:
        name:
          type: string
          title: Project Name
          description: e.g., "my-vue-app"
        description:
          type: string
          title: Description
          ui:widget: textarea
        useRouter:
          type: boolean
          title: Add Vue Router
          default: true
        usePinia:
          type: boolean
          title: Add Pinia (State Management)
          default: true

    - title: Repository
      required: [repoUrl]
      properties:
        repoUrl:
          type: string
          title: GitHub Repository URL
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: [github.com]

  # 执行步骤
  steps:
    - id: fetch-template
      name: Fetch Vue Template
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          useRouter: ${{ parameters.useRouter }}
          usePinia: ${{ parameters.usePinia }}

    - id: customize-package
      name: Customize package.json
      action: fs:modify
      input:
        files: [package.json]
        write: 
          - path: package.json
            content: |
              {
                "name": "{{values.name}}",
                "version": "0.1.0",
                "description": "{{values.description}}",
                "scripts": {
                  "dev": "vite",
                  "build": "vite build"
                },
                "dependencies": {
                  "vue": "^3.4.0",
                  "vue-router": "{{#values.useRouter}}4.2.0{{/values.useRouter}}",
                  "pinia": "{{#values.usePinia}}2.1.0{{/values.usePinia}}"
                },
                "devDependencies": {
                  "vite": "^5.0.0",
                  "@vitejs/plugin-vue": "^4.5.0",
                  "eslint": "^8.56.0"
                }
              }

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
